module.exports = [
  {
    name: "Financial Support",
    slug: "financial",
    description: "Money support for rent, bills, education, and urgent living expenses",
    emoji: "💰",
    icon: "💰",
    order: 1,
    isActive: true,
  },
  {
    name: "Medical Support",
    slug: "medical",
    description: "Medicines, treatment, therapy, and healthcare expenses",
    emoji: "💊",
    icon: "💊",
    order: 2,
    isActive: true,
  },
  {
    name: "Surgery",
    slug: "surgery",
    description: "Operations, procedures, and long-term treatment plans",
    emoji: "🏥",
    icon: "🏥",
    order: 3,
    isActive: true,
  },
  {
    name: "Physical Support",
    slug: "physical",
    description: "Clothes, blankets, school supplies, furniture, and essential items",
    emoji: "👕",
    icon: "👕",
    order: 4,
    isActive: true,
  },
  {
    name: "Emergency Relief",
    slug: "emergency",
    description: "Urgent support during crises, displacement, fires, floods, or disasters",
    emoji: "🚨",
    icon: "🚨",
    order: 5,
    isActive: true,
  },
  {
    name: "Blood Donation",
    slug: "blood",
    description: "Blood donation requests and urgent medical matching needs",
    emoji: "🩸",
    icon: "🩸",
    order: 6,
    isActive: true,
  },
  {
    name: "Education",
    slug: "education",
    description: "School fees, books, stationery, transport, and study support",
    emoji: "📚",
    icon: "📚",
    order: 7,
    isActive: true,
  },
];
